### ISSUE TITLE
Window Size for `zstd-d`

### ISSUE THREAD

**Issue by felixhandte** [nidhijaju/draft-zstd-window-size#1]
The Compression Dictionary Transport spec introduces a new encoding scheme `zstd-d`. We may want to clarify the window limits for that scheme as well (either in this draft or in the CDT draft).

Probably the right answer is something like 8 MB or 2 * the dictionary size if one is in use, to allow delta-ing of larger resources.

**Comment by nidhijaju** [comment]
That's a good point!
I think in Chrome we ended up using [max(dictionary size, 8 MB)](https://source.chromium.org/chromium/chromium/src/+/main:net/filter/zstd_source_stream.cc;l=49-57;drc=f88f2c49794bb22673f9048f7ee0d0e8279582c7) if a dictionary is in use, or 8 MB otherwise.

I think that should be added to the Compression Dictionary Transport spec, since it's not published yet and that's where the Content-Encoding token for `zstd-d` is being added. I just filed [an issue](https://github.com/httpwg/http-extensions/issues/2754) there.
